/*
 * The MIT License (MIT)
 * Copyright (c) 2024 Karl STEIN
 */

import errors, {
  ERROR_FIELD_ADDITIONAL_PROPERTIES,
  ERROR_FIELD_DENIED,
  ERROR_FIELD_ENUM,
  ERROR_FIELD_EXCLUSIVE_MAXIMUM,
  ERROR_FIELD_EXCLUSIVE_MINIMUM,
  ERROR_FIELD_FORMAT,
  ERROR_FIELD_LENGTH,
  ERROR_FIELD_MAX_ITEMS,
  ERROR_FIELD_MAX_LENGTH,
  ERROR_FIELD_MAX_WORDS,
  ERROR_FIELD_MAXIMUM,
  ERROR_FIELD_MIN_ITEMS,
  ERROR_FIELD_MIN_LENGTH,
  ERROR_FIELD_MIN_WORDS,
  ERROR_FIELD_MINIMUM,
  ERROR_FIELD_MULTIPLE_OF,
  ERROR_FIELD_PATTERN,
  ERROR_FIELD_PATTERN_PROPERTIES,
  ERROR_FIELD_PROPERTIES,
  ERROR_FIELD_REQUIRED,
  ERROR_FIELD_TYPE,
  ERROR_FIELD_UNIQUE_ITEMS,
  ERROR_SCHEMA_VALIDATION
} from './errors'
import { getErrorMessage, setLocaleMessages } from './locale'
import SchemaError from './errors/SchemaError'
import JSONSchema from './JSONSchema'
import Schema from './Schema'
import ValidationError from './errors/ValidationError'

export {
  ERROR_FIELD_ADDITIONAL_PROPERTIES,
  ERROR_FIELD_DENIED,
  ERROR_FIELD_ENUM,
  ERROR_FIELD_EXCLUSIVE_MINIMUM,
  ERROR_FIELD_EXCLUSIVE_MAXIMUM,
  ERROR_FIELD_FORMAT,
  ERROR_FIELD_LENGTH,
  ERROR_FIELD_MAXIMUM,
  ERROR_FIELD_MAX_ITEMS,
  ERROR_FIELD_MAX_LENGTH,
  ERROR_FIELD_MAX_WORDS,
  ERROR_FIELD_MINIMUM,
  ERROR_FIELD_MIN_ITEMS,
  ERROR_FIELD_MIN_LENGTH,
  ERROR_FIELD_MIN_WORDS,
  ERROR_FIELD_MULTIPLE_OF,
  ERROR_FIELD_PATTERN,
  ERROR_FIELD_PATTERN_PROPERTIES,
  ERROR_FIELD_PROPERTIES,
  ERROR_FIELD_REQUIRED,
  ERROR_FIELD_TYPE,
  ERROR_FIELD_UNIQUE_ITEMS,
  ERROR_SCHEMA_VALIDATION,
  errors,
  getErrorMessage,
  setLocaleMessages,
  JSONSchema,
  Schema,
  SchemaError,
  ValidationError
}
